name: Build and test

on:
  push:
    branches:
      - main
      - develop
      - feature_*

  pull_request:
    branches:
      - main
      - develop
      - feature_*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare
        run: |
          sudo apt install lcov libsofthsm2 libsystemd-dev -y
          pip install conan

      - name: Build and test
        run: |
          mkdir build

          conan profile detect --force

          conan install ./conan/ --output-folder build --settings=build_type=Debug --options=with_poco=True --build=missing
          cmake ./ -B./build/ -DCMAKE_TOOLCHAIN_FILE=./conan_toolchain.cmake -DWITH_TEST=ON -DWITH_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug

          cd build
          make; make tests; make coverage

      - name: Upload codecov report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/coverage.total
