name: Static analysis
on:
  push:
    branches:
      - main
      - develop
      - feature_*

  pull_request:
    branches:
      - main
      - develop
      - feature_*

jobs:
  cpp-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: |
          sudo apt install cppcheck -y

      - name: Run cppcheck
        run: |
          cppcheck --enable=all --inline-suppr -I src --std=c++17 --error-exitcode=1 \
                   --suppressions-list=./suppressions.txt src
